repos:
  - repo: local
    hooks:
      - id: poetry-check
        name: poetry-check
        description: run poetry check to validate config
        entry: poetry check
        language: python
        pass_filenames: false
        files: ^(.*/)?(poetry\.lock|pyproject\.toml)$
      - id: poetry-flake8
        name: poetry-flake8
        description: run linter
        entry: poetry run flake8
        pass_filenames: false
        language: python
      - id: poetry-pytest
        name: poetry-pytest
        description: run pytest
        entry: poetry run pytest
        language: python
        pass_filenames: false
